//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.0
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MC.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_HOME_EXIT {
            get {
                return ResourceManager.GetString("MENU_HOME_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_HOME_PREFERENCE {
            get {
                return ResourceManager.GetString("MENU_HOME_PREFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通学 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MENU_HOME_WORLD {
            get {
                return ResourceManager.GetString("MENU_HOME_WORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム メニュー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_HOME {
            get {
                return ResourceManager.GetString("MESSAGE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定項目はありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_PREFERENCE {
            get {
                return ResourceManager.GetString("MESSAGE_PREFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MATH.SC を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_START {
            get {
                return ResourceManager.GetString("MESSAGE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   そいえば俺はニートだった。残念！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_WORLD {
            get {
                return ResourceManager.GetString("MESSAGE_WORLD", resourceCulture);
            }
        }
    }
}
