//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.0
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.MockServer.Res.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MC.MockServer.Res.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   れい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM0_0 {
            get {
                return ResourceManager.GetString("NUM0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゼロ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM0_1 {
            get {
                return ResourceManager.GetString("NUM0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   零 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM0_2 {
            get {
                return ResourceManager.GetString("NUM0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM0_3 {
            get {
                return ResourceManager.GetString("NUM0_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZERO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM0_4 {
            get {
                return ResourceManager.GetString("NUM0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM1_0 {
            get {
                return ResourceManager.GetString("NUM1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ひとつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM1_1 {
            get {
                return ResourceManager.GetString("NUM1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM1_2 {
            get {
                return ResourceManager.GetString("NUM1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM1_3 {
            get {
                return ResourceManager.GetString("NUM1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM2_0 {
            get {
                return ResourceManager.GetString("NUM2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ふたつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM2_1 {
            get {
                return ResourceManager.GetString("NUM2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   二 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM2_2 {
            get {
                return ResourceManager.GetString("NUM2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM2_3 {
            get {
                return ResourceManager.GetString("NUM2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   さん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM3_0 {
            get {
                return ResourceManager.GetString("NUM3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   みっつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM3_1 {
            get {
                return ResourceManager.GetString("NUM3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   三 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM3_2 {
            get {
                return ResourceManager.GetString("NUM3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM3_3 {
            get {
                return ResourceManager.GetString("NUM3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM4_0 {
            get {
                return ResourceManager.GetString("NUM4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   よっつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM4_1 {
            get {
                return ResourceManager.GetString("NUM4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   よん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM4_2 {
            get {
                return ResourceManager.GetString("NUM4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   四 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM4_3 {
            get {
                return ResourceManager.GetString("NUM4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM4_4 {
            get {
                return ResourceManager.GetString("NUM4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM5_0 {
            get {
                return ResourceManager.GetString("NUM5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いつつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM5_1 {
            get {
                return ResourceManager.GetString("NUM5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   五 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM5_2 {
            get {
                return ResourceManager.GetString("NUM5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM5_3 {
            get {
                return ResourceManager.GetString("NUM5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ろく に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM6_0 {
            get {
                return ResourceManager.GetString("NUM6_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   むっつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM6_1 {
            get {
                return ResourceManager.GetString("NUM6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   六 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM6_2 {
            get {
                return ResourceManager.GetString("NUM6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM6_3 {
            get {
                return ResourceManager.GetString("NUM6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なな に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM7_0 {
            get {
                return ResourceManager.GetString("NUM7_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ななつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM7_1 {
            get {
                return ResourceManager.GetString("NUM7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM7_2 {
            get {
                return ResourceManager.GetString("NUM7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   七 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM7_3 {
            get {
                return ResourceManager.GetString("NUM7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM7_4 {
            get {
                return ResourceManager.GetString("NUM7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はち に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM8_0 {
            get {
                return ResourceManager.GetString("NUM8_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やっつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM8_1 {
            get {
                return ResourceManager.GetString("NUM8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   八 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM8_2 {
            get {
                return ResourceManager.GetString("NUM8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM8_3 {
            get {
                return ResourceManager.GetString("NUM8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   きゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM9_0 {
            get {
                return ResourceManager.GetString("NUM9_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここのつ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM9_1 {
            get {
                return ResourceManager.GetString("NUM9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   九 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM9_2 {
            get {
                return ResourceManager.GetString("NUM9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   9 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUM9_3 {
            get {
                return ResourceManager.GetString("NUM9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   じゅう に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUMA_0 {
            get {
                return ResourceManager.GetString("NUMA_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とお に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUMA_1 {
            get {
                return ResourceManager.GetString("NUMA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   十 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUMA_2 {
            get {
                return ResourceManager.GetString("NUMA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いっぱい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUMB_0 {
            get {
                return ResourceManager.GetString("NUMB_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   たくさん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUMB_1 {
            get {
                return ResourceManager.GetString("NUMB_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指足りない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NUMB_2 {
            get {
                return ResourceManager.GetString("NUMB_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このすうじはなんて読みますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUESTION1_1_1 {
            get {
                return ResourceManager.GetString("QUESTION1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これはどのすうじですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUESTION1_1_2 {
            get {
                return ResourceManager.GetString("QUESTION1_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いくつありますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QUESTION1_2 {
            get {
                return ResourceManager.GetString("QUESTION1_2", resourceCulture);
            }
        }
    }
}
