//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MC.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   正答数 {0} / {1} 問題数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CORRECT_COUNT {
            get {
                return ResourceManager.GetString("MSG_CORRECT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不合格 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_FAILED {
            get {
                return ResourceManager.GetString("MSG_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合格 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PASSED {
            get {
                return ResourceManager.GetString("MSG_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PRACTICE_ANSWER1 {
            get {
                return ResourceManager.GetString("MSG_PRACTICE_ANSWER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PRACTICE_ANSWER2 {
            get {
                return ResourceManager.GetString("MSG_PRACTICE_ANSWER2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PRACTICE_ANSWER3 {
            get {
                return ResourceManager.GetString("MSG_PRACTICE_ANSWER3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PRACTICE_ANSWER4 {
            get {
                return ResourceManager.GetString("MSG_PRACTICE_ANSWER4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここに問題が に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PRACTICE_CAPTION {
            get {
                return ResourceManager.GetString("MSG_PRACTICE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_PRACTICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MSG_PRACTICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/AreaPage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_AREA {
            get {
                return ResourceManager.GetString("PAGE_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/HomePage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_HOME {
            get {
                return ResourceManager.GetString("PAGE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/LogoPage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_LOGO {
            get {
                return ResourceManager.GetString("PAGE_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/PracticePage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_PRACTICE {
            get {
                return ResourceManager.GetString("PAGE_PRACTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/Practice/CountDownPage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_PRACTICE_COUNT {
            get {
                return ResourceManager.GetString("PAGE_PRACTICE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/Practice/SingleResult.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_PRACTICE_SINGLERESULT {
            get {
                return ResourceManager.GetString("PAGE_PRACTICE_SINGLERESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/Practice/WaitPage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_PRACTICE_WAIT {
            get {
                return ResourceManager.GetString("PAGE_PRACTICE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/PreferencePage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_PREFERENCE {
            get {
                return ResourceManager.GetString("PAGE_PREFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pages/WorldPage.xaml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAGE_WORLD {
            get {
                return ResourceManager.GetString("PAGE_WORLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MC.Desktop.Res.MC_1.ico に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RES_ICON {
            get {
                return ResourceManager.GetString("RES_ICON", resourceCulture);
            }
        }
    }
}
